### PR TITLE
readme.md file updated with a hacktoberfest image and some emoji's

### PR DESCRIPTION
**Pull request by pantbibek21**
Sir, I have added a banner of hacktoberfest and some emoji's. Please, review and accept if everything is okay to you.

### CODE REVIEW

**Comment by pantbibek21** [comment]
Sir, you can use label "hacktoberfest" for the issue and "hacktoberfest-accepted" while accepting PR. Since hacktoberfest is going on, your repo also mentions and supports hacktoberfest. Just reminded if you missed it, sir.

**Comment by souvikrajsingh** [comment]
> Sir, you can use label "hacktoberfest" for the issue and "hacktoberfest-accepted" while accepting PR. Since hacktoberfest is going on, your repo also mentions and supports hacktoberfest. Just reminded if you missed it, sir.

Thank you Bibek for reminding me, missed it out !!

**Comment by pantbibek21** [comment]
@souvikrajsingh sir, is there anything I have to update? You haven't accepted this PR. I hope you don't forgot sir : )

**Comment by souvikrajsingh** [comment]
> @souvikrajsingh sir, is there anything I have to update? You haven't accepted this PR. I hope you don't forgot sir : )

got caught up in a few things bibek, merging your PR now.

How's hacktoberfest going on for you ?

**Pull request merged**
