### PR TITLE
Added an opportunity and a small change in CSS

### PR DESCRIPTION
**Pull request by pankti13**
Issue 3 Resolved

### CODE REVIEW

**Comment by souvikrajsingh** [comment]
Hey pankti @pankti13 I love your PR but there is a conflict arising in the index.html file . Do  you think you can refactor it ?

**Comment by pankti13** [comment]
Sir, @souvikrajsingh , I have tried to resolve the conflicts to the best of my knowledge. Please let me know if it was fruitful.

**Comment by souvikrajsingh** [comment]
> Sir, @souvikrajsingh , I have tried to resolve the conflicts to the best of my knowledge. Please let me know if it was fruitful.

@pankti13 You should change the branch before contributing to the repo

I would suggest start from the beginning 

after you fork and clone the file pankti, you'll see you are at master branch on your git bash (master)

create a new branch by using the command 

`git branch <new-branch-name>`

change the head to the new branch

`git checkout <new-branch-name>`


now make the changes and submit  a PR ! I would love to have it merged in this Repo

**Comment by pankti13** [comment]
Thank you sir for pointing out to the mistakes, i will surely submit a
fresh PR without fail

**Comment by souvikrajsingh** [comment]
Will happily merge it 😄

**Comment by pankti13** [comment]
Thank you!

**Pull request closed without merging**
