### PR TITLE
 Secondphase

### PR DESCRIPTION
**Pull request by Khadeeejah**
i created the second phase of the  Outreachy internship, and formatted the code
 kindly review and add the hacktoberfest tag for it to be accepted

@souvikrajsingh

### CODE REVIEW

**Comment by souvikrajsingh** [comment]
hey @Khadeeejah a Conflict arised, so had to solve it ! thank you so much for Adding the outreachy Program! 

Share this repo with your friends who are participating in hacktoberfest!

Thanks for contributing! cheers

**Comment by Khadeeejah** [comment]
Hi @souvikrajsingh  sorry about that I'm still open to contributing more if you don't mind and will also share it with my friends

**Comment by souvikrajsingh** [comment]
Sure thing @Khadeeejah, would you like to add more opportunities, work on something else?

**Comment by Khadeeejah** [comment]
> Sure thing @Khadeeejah, would you like to add more opportunities, work on something else? 

I would add more opportunities and pick other issues.
Thank you

**Comment by souvikrajsingh** [comment]
Perfect!

**Comment by Khadeeejah** [comment]
> Perfect!
> 
> 

I checked my hacktoberfest dashboard and I noticed this PR wasn't accepted, do you have any idea of what may be wrong

**Comment by souvikrajsingh** [comment]
> > Perfect!
> 
> I checked my hacktoberfest dashboard and I noticed this PR wasn't accepted, do you have any idea of what may be wrong

it gets updates every fifteen minutes, check after some time.
What about the PR earlier?

**Comment by Khadeeejah** [comment]
> > > Perfect!
> 
> > 
> 
> > I checked my hacktoberfest dashboard and I noticed this PR wasn't accepted, do you have any idea of what may be wrong
> 
> 
> 
> it gets updates every fifteen minutes, check after some time.
> 
> What about the PR earlier? 

It's in the waiting stage... 5 more days..
Thank you I will check back later

**Comment by souvikrajsingh** [comment]
> > > > Perfect!
> > 
> > 
> > > 
> > 
> > 
> > > I checked my hacktoberfest dashboard and I noticed this PR wasn't accepted, do you have any idea of what may be wrong
> > 
> > 
> > it gets updates every fifteen minutes, check after some time.
> > What about the PR earlier?
> 
> It's in the waiting stage... 5 more days.. Thank you I will check back later

Let me know if you need any help. 
Will try to assist you as much as possible 

get started with your contributions! cheers

**Pull request merged**
