### PR TITLE
added oppertunity

### PR DESCRIPTION
**Pull request by ItsAshrafSyed**

### CODE REVIEW

**Comment by souvikrajsingh** [comment]
@ItsAshrafSyed your I'm sorry but some Conflicts arose, I love your PR but do you think you can refactor it?

**Comment by souvikrajsingh** [comment]
> @ItsAshrafSyed your I'm sorry but some Conflicts arose, I love your PR but do you think you can refactor it?

you are commiting directly to the "master" branch ashraf.

I would suggest you make a PR again with the added opportunities you want to add, but before that change the branch

`git branch <your-branch-name>`
`git checkout <your-branch-name>`

**Comment by ItsAshrafSyed** [comment]
Can you pls give it a try now

**Review by souvikrajsingh — APPROVED** [review]

**Comment by souvikrajsingh** [comment]
> Can you pls give it a try now

sadly it's not working!

I would suggest you give it a fresh start, delete the local repository you have on your system and fork and clone this repo again. before you start making any changes Ashraf @ItsAshrafSyed create a bew branch by using the command
`git branch <your-branch-name>`
then change the head to your-new-branch
`git checkout <your-branch-name>`
you'll see the master changes to your-new-branch name

make your changes and make a PR!

**Pull request closed without merging**
